# Generated by Django 5.2.3 on 2025-06-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
