# Generated by Django 5.2.3 on 2025-06-30 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookies', '0003_alter_choice_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='probability',
        ),
        migrations.AddField(
            model_name='bet',
            name='win_probability',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
