# Generated by Django 5.2.3 on 2025-06-30 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookies', '0004_remove_choice_probability_bet_win_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='win_probability',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
