# Generated by Django 5.2.3 on 2025-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookies', '0005_alter_bet_win_probability_alter_choice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='win_condition',
            field=models.BooleanField(default=False),
        ),
    ]
