# Generated by Django 5.2.3 on 2025-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookies', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=11),
        ),
    ]
